service: LanguageAppPrototype
frameworkVersion: ">=1.46.0"

# Specifies the cloud provider and runtime details for our serverless implementation
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  profile: LanguageAppAdmin

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
      Resource: arn:aws:dynamodb:*:*:table/*-language-app-*
    - Effect: Allow
      Action:
        - translate:TranslateText
      Resource: "*"

plugins:
  - serverless-appsync-plugin

functions:
  lambdaGraphQl:
    handler: handler.lambdaResolver
    environment:
      CHATS_TABLE: ${opt:stage, self:provider.stage}-language-app-chats
      USERS_TABLE: ${opt:stage, self:provider.stage}-language-app-users
  streamProcessor:
    timeout: 15
    handler: handler.streamProcessor
    environment:
      CHATS_TABLE: ${opt:stage, self:provider.stage}-language-app-chats
      USERS_TABLE: ${opt:stage, self:provider.stage}-language-app-users
    events:
      - stream:
          type: dynamodb
          batchSize: 10
          startingPosition: TRIM_HORIZON
          arn:
            Fn::GetAtt:
              - chatTable
              - StreamArn

custom:
  stage: ${opt:stage, self:provider.stage}
  chatsTableName: ${self:custom.stage}-language-app-chats
  usersTableName: ${self:custom.stage}-language-app-users
  appSync:
    name: LanguageAppPrototypeAppSync
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: !Ref CognitoUserPool
      # appIdClientRegex: ""
    dataSources:
      - type: AMAZON_DYNAMODB
        name: chatsSource
        config:
          tableName: ${self:custom.chatsTableName}
      - type: AMAZON_DYNAMODB
        name: usersSource
        config:
          tableName: ${self:custom.usersTableName}
      - type: AWS_LAMBDA
        name: lambdaSource
        description: 'Lambda DataSource'
        config:
          functionName: lambdaGraphQl
      - type: NONE
        name: noneSource
    mappingTemplates:
      - dataSource: chatsSource
        type: Query
        field: listMessages # from the query in schema.graphql
        request: "list_messages/request.vtl"
        response: "list_messages/response.vtl"
      - dataSource: chatsSource
        type: Mutation
        field: createMessage # from the mutation in schema.graphql
        request: "create_message/request.vtl"
        response: "create_message/response.vtl"
      - dataSource: noneSource
        type: Subscription
        field: createdMessage # from the subscription in schema.graphql
        request: "get_created_message/request.vtl"
        response: "get_created_message/response.vtl"
      - dataSource: lambdaSource
        type: Mutation
        field: createChatPrivate # from the mutation in schema.graphql
        request: "create_chat_private/request.vtl"
        response: "create_chat_private/response.vtl"
      - dataSource: chatsSource
        type: Query
        field: listSelfChatMembers # from the query in schema.graphql
        request: "list_self_chat_members/request.vtl"
        response: "list_self_chat_members/response.vtl"
      - dataSource: chatsSource
        type: Query
        field: getChats # from the query in schema.graphql
        request: "get_chats/request.vtl"
        response: "get_chats/response.vtl"
      - dataSource: usersSource
        type: Mutation
        field: putUser # from the mutation in schema.graphql
        request: "put_user/request.vtl"
        response: "put_user/response.vtl"
      - dataSource: chatsSource
        type: Mutation
        field: createChatGroupWithMembers # from the mutation in schema.graphql
        request: "create_chat_group_with_members/request.vtl"
        response: "create_chat_group_with_members/response.vtl"
      - dataSource: chatsSource
        type: Mutation
        field: putMembersToChat # from the mutation in schema.graphql
        request: "put_members_to_chat/request.vtl"
        response: "put_members_to_chat/response.vtl"
      - dataSource: usersSource
        type: Query
        field: searchUsers # from the query in schema.graphql
        request: "search_users/request.vtl"
        response: "search_users/response.vtl"
      - dataSource: usersSource
        type: Query
        field: getUser # from the query in schema.graphql
        request: "get_user/request.vtl"
        response: "get_user/response.vtl"
      - dataSource: lambdaSource
        type: Query
        field: getChatPrivate # from the query in schema.graphql
        request: "get_chat_private/request.vtl"
        response: "get_chat_private/response.vtl"
      - dataSource: chatsSource
        type: Query
        field: getChat # from the query in schema.graphql
        request: "get_chat/request.vtl"
        response: "get_chat/response.vtl"
      - dataSource: chatsSource
        type: Query
        field: getChatMembers # from the query in schema.graphql
        request: "get_chat_members/request.vtl"
        response: "get_chat_members/response.vtl"
    substitutions:
      chatsTableName: "${self:custom.chatsTableName}"
      usersTableName: "${self:custom.usersTableName}"

# AWS CloudFormation configuration
resources:
  - ${file(resources/cognito.yaml)}
  - ${file(resources/dynamodb-tables.yaml)}
