Resources:
  chatTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.chatsTableName}
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
        - AttributeName: sortKey
          AttributeType: S
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
        - AttributeName: sortKey
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: invertedIndex # Currently without sort key because it's not needed
        KeySchema:
        - AttributeName: sortKey
          KeyType: HASH
        Projection:
          ProjectionType: ALL #TODO: Use INCLUDE and set NonKeyAttributes
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1